global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using MosaicDroid.GUI.Models;
global using MosaicDroid.GUI.DataContracts;
global using MosaicDroid.GUI.DataContracts.Serialization;
global using MosaicDroid.GUI.Services.Caching;
global using MosaicDroid.GUI.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
